### ISSUE TITLE
Syntax Error on bookings table

### ISSUE THREAD

**Issue by TomGrozev** [daveroverts/bmac#222]
It seems that there is a syntax error when on the bookings table (i.e. /bookings). Get this error:  `syntax error, unexpected 'Event' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) (View: /var/www/booking/resources/views/booking/overview.blade.php)`

Using dev branch (latest). Master branch has no difference.

**Comment by daveroverts** [comment]
@TomGrozev I just cloned the repository on a random PC and set up what's needed. I also created 2 different events (one of them multi-city, because that one works different), but don't see any errors.

That view nowadays loads in a Liverwire component (introduced by #191 and added to master in [v2.1.0](https://github.com/daveroverts/bmac/releases/tag/v2.1.0)), did you do `composer install` after getting the latest changes?
